data = [
    {'name': 'Pablo Picasso', 'follower_count': 1200000, 'description': 'Renowned painter and sculptor.', 'country': 'Spain'},
    {'name': 'J.K. Rowling', 'follower_count': 5000000, 'description': 'Author of the Harry Potter series.', 'country': 'United Kingdom'},
    {'name': 'Michael Jordan', 'follower_count': 2300000, 'description': 'Legendary basketball player.', 'country': 'United States'},
    {'name': 'Inception', 'follower_count': 1500000, 'description': 'Mind-bending thriller movie.', 'country': 'United States'},
    {'name': 'Game of Thrones', 'follower_count': 8000000, 'description': 'Epic fantasy TV series.', 'country': 'United States'},
    {'name': 'Leonardo DiCaprio', 'follower_count': 12000000, 'description': 'Award-winning actor.', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 15000000, 'description': 'International music superstar.', 'country': 'United States'},
    {'name': 'George Washington', 'follower_count': 1000000, 'description': 'First President of the United States.', 'country': 'United States'},
    {'name': 'Google', 'follower_count': 10000000, 'description': 'Leading tech company.', 'country': 'United States'},
    {'name': 'iPhone', 'follower_count': 20000000, 'description': 'Popular smartphone by Apple.', 'country': 'United States'},
    {'name': 'The Legend of Zelda', 'follower_count': 900000, 'description': 'Classic adventure video game.', 'country': 'Japan'},
    {'name': 'Muhammad Ali', 'follower_count': 3000000, 'description': 'Legendary boxer and cultural icon.', 'country': 'United States'},
    {'name': 'Vincent van Gogh', 'follower_count': 2000000, 'description': 'Famous post-impressionist painter.', 'country': 'Netherlands'},
    {'name': 'The Hobbit', 'follower_count': 1200000, 'description': 'Classic fantasy novel by J.R.R. Tolkien.', 'country': 'United Kingdom'},
    {'name': 'Serena Williams', 'follower_count': 4000000, 'description': 'Champion tennis player.', 'country': 'United States'},
    {'name': 'The Matrix', 'follower_count': 2200000, 'description': 'Sci-fi action movie.', 'country': 'United States'},
    {'name': 'Friends', 'follower_count': 5000000, 'description': 'Popular TV sitcom.', 'country': 'United States'},
    {'name': 'Brad Pitt', 'follower_count': 10000000, 'description': 'Famous Hollywood actor.', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 20000000, 'description': 'Pop music sensation.', 'country': 'United States'},
    {'name': 'Abraham Lincoln', 'follower_count': 1500000, 'description': '16th President of the United States.', 'country': 'United States'},
    {'name': 'Amazon', 'follower_count': 8000000, 'description': 'Global e-commerce giant.', 'country': 'United States'},
    {'name': 'Samsung Galaxy', 'follower_count': 10000000, 'description': 'Popular Android smartphone.', 'country': 'South Korea'},
    {'name': 'Super Mario', 'follower_count': 2000000, 'description': 'Iconic video game character.', 'country': 'Japan'},
    {'name': 'Mike Tyson', 'follower_count': 3000000, 'description': 'Former heavyweight boxing champion.', 'country': 'United States'},
    {'name': 'Claude Monet', 'follower_count': 1800000, 'description': 'Founder of French Impressionist painting.', 'country': 'France'},
    {'name': '1984', 'follower_count': 1100000, 'description': 'Dystopian novel by George Orwell.', 'country': 'United Kingdom'},
    {'name': 'Usain Bolt', 'follower_count': 4000000, 'description': 'Fastest man in the world.', 'country': 'Jamaica'},
    {'name': 'The Godfather', 'follower_count': 2500000, 'description': 'Classic crime film.', 'country': 'United States'},
    {'name': 'Breaking Bad', 'follower_count': 6000000, 'description': 'Critically acclaimed TV series.', 'country': 'United States'},
    {'name': 'Angelina Jolie', 'follower_count': 12000000, 'description': 'Renowned actress and humanitarian.', 'country': 'United States'},
    {'name': 'Ed Sheeran', 'follower_count': 13000000, 'description': 'Popular singer-songwriter.', 'country': 'United Kingdom'},
    {'name': 'John F. Kennedy', 'follower_count': 1700000, 'description': '35th President of the United States.', 'country': 'United States'},
    {'name': 'Microsoft', 'follower_count': 9000000, 'description': 'Leading software company.', 'country': 'United States'},
    {'name': 'Google Pixel', 'follower_count': 5000000, 'description': 'Smartphone developed by Google.', 'country': 'United States'},
    {'name': 'Pac-Man', 'follower_count': 1200000, 'description': 'Classic arcade game.', 'country': 'Japan'},
    {'name': 'Floyd Mayweather', 'follower_count': 4000000, 'description': 'Undefeated boxing champion.', 'country': 'United States'},
    {'name': 'Salvador Dalí', 'follower_count': 1900000, 'description': 'Surrealist artist.', 'country': 'Spain'},
    {'name': 'To Kill a Mockingbird', 'follower_count': 1000000, 'description': 'Novel by Harper Lee.', 'country': 'United States'},
    {'name': 'Roger Federer', 'follower_count': 8000000, 'description': 'Tennis legend.', 'country': 'Switzerland'},
    {'name': 'Star Wars', 'follower_count': 10000000, 'description': 'Epic space-opera franchise.', 'country': 'United States'},
    {'name': 'Stranger Things', 'follower_count': 9000000, 'description': 'Popular sci-fi horror series.', 'country': 'United States'},
    {'name': 'Johnny Depp', 'follower_count': 11000000, 'description': 'Versatile actor.', 'country': 'United States'},
    {'name': 'Adele', 'follower_count': 14000000, 'description': 'Award-winning singer.', 'country': 'United Kingdom'},
    {'name': 'Franklin D. Roosevelt', 'follower_count': 2000000, 'description': '32nd President of the United States.', 'country': 'United States'},
    {'name': 'Facebook', 'follower_count': 22000000, 'description': 'Social media giant.', 'country': 'United States'},
    {'name': 'Huawei P30', 'follower_count': 4000000, 'description': 'Popular smartphone by Huawei.', 'country': 'China'},
    {'name': 'Call of Duty', 'follower_count': 7000000, 'description': 'Popular first-person shooter game.', 'country': 'United States'},
    {'name': 'Manny Pacquiao', 'follower_count': 5000000, 'description': 'Champion boxer and politician.', 'country': 'Philippines'},
    {'name': 'Rembrandt', 'follower_count': 1600000, 'description': 'Dutch Golden Age painter.', 'country': 'Netherlands'},
    {'name': 'Moby-Dick', 'follower_count': 800000, 'description': 'Novel by Herman Melville.', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 18000000, 'description': 'Football superstar.', 'country': 'Portugal'},
    {'name': 'Avatar', 'follower_count': 8500000, 'description': 'Highest-grossing film of all time.', 'country': 'United States'},
    {'name': 'The Crown', 'follower_count': 6000000, 'description': 'Historical drama series.', 'country': 'United Kingdom'},
    {'name': 'Scarlett Johansson', 'follower_count': 9000000, 'description': 'A-list actress.', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 20000000, 'description': 'Pop music icon.', 'country': 'Canada'},
    {'name': 'Winston Churchill', 'follower_count': 2500000, 'description': 'Former Prime Minister of the United Kingdom.', 'country': 'United Kingdom'},
    {'name': 'Tesla', 'follower_count': 11000000, 'description': 'Innovative electric car company.', 'country': 'United States'},
    {'name': 'Nokia 3310', 'follower_count': 2000000, 'description': 'Classic mobile phone.', 'country': 'Finland'},
    {'name': 'Fortnite', 'follower_count': 15000000, 'description': 'Massively popular battle royale game.', 'country': 'United States'},
    {'name': 'Jack Dempsey', 'follower_count': 800000, 'description': 'Legendary boxer.', 'country': 'United States'},
    {'name': 'Andy Warhol', 'follower_count': 1700000, 'description': 'Leading figure in pop art.', 'country': 'United States'},
    {'name': 'War and Peace', 'follower_count': 900000, 'description': 'Epic novel by Leo Tolstoy.', 'country': 'Russia'},
    {'name': 'Lionel Messi', 'follower_count': 20000000, 'description': 'Football legend.', 'country': 'Argentina'},
    {'name': 'Titanic', 'follower_count': 8000000, 'description': 'Epic romance/disaster film.', 'country': 'United States'},
    {'name': 'The Mandalorian', 'follower_count': 7000000, 'description': 'Hit Star Wars TV series.', 'country': 'United States'},
    {'name': 'Robert Downey Jr.', 'follower_count': 12000000, 'description': 'Marvel superhero actor.', 'country': 'United States'},
    {'name': 'Rihanna', 'follower_count': 17000000, 'description': 'Barbadian singer and businesswoman.', 'country': 'Barbados'},
    {'name': 'Theodore Roosevelt', 'follower_count': 2000000, 'description': '26th President of the United States.', 'country': 'United States'},
    {'name': 'Apple', 'follower_count': 25000000, 'description': 'Tech company known for iPhones and Macs.', 'country': 'United States'},
    {'name': 'Sony Xperia', 'follower_count': 3000000, 'description': 'High-end smartphone by Sony.', 'country': 'Japan'},
    {'name': 'Minecraft', 'follower_count': 20000000, 'description': 'Best-selling video game of all time.', 'country': 'Sweden'},
    {'name': 'Joe Frazier', 'follower_count': 1500000, 'description': 'Former heavyweight boxing champion.', 'country': 'United States'},
    {'name': 'Jackson Pollock', 'follower_count': 1100000, 'description': 'Abstract expressionist painter.', 'country': 'United States'},
    {'name': 'Pride and Prejudice', 'follower_count': 1400000, 'description': 'Classic novel by Jane Austen.', 'country': 'United Kingdom'},
    {'name': 'Pele', 'follower_count': 12000000, 'description': 'Football legend.', 'country': 'Brazil'},
    {'name': 'Jurassic Park', 'follower_count': 7500000, 'description': 'Blockbuster dinosaur film.', 'country': 'United States'},
    {'name': 'The Witcher', 'follower_count': 6000000, 'description': 'Fantasy TV series based on books.', 'country': 'Poland'},
    {'name': 'Tom Cruise', 'follower_count': 10000000, 'description': 'Hollywood action star.', 'country': 'United States'},
    {'name': 'Lady Gaga', 'follower_count': 18000000, 'description': 'Pop icon and actress.', 'country': 'United States'},
    {'name': 'Dwight D. Eisenhower', 'follower_count': 1700000, 'description': '34th President of the United States.', 'country': 'United States'},
    {'name': 'IBM', 'follower_count': 7000000, 'description': 'Global technology company.', 'country': 'United States'},
    {'name': 'HTC One', 'follower_count': 2000000, 'description': 'Popular smartphone by HTC.', 'country': 'Taiwan'},
    {'name': 'The Sims', 'follower_count': 8000000, 'description': 'Life simulation video game.', 'country': 'United States'},
    {'name': 'Rocky Marciano', 'follower_count': 1200000, 'description': 'Undefeated heavyweight boxing champion.', 'country': 'United States'},
    {'name': 'Henri Matisse', 'follower_count': 1300000, 'description': 'French artist known for his use of color.', 'country': 'France'},
    {'name': 'Don Quixote', 'follower_count': 1100000, 'description': 'Classic novel by Miguel de Cervantes.', 'country': 'Spain'},
    {'name': 'David Beckham', 'follower_count': 15000000, 'description': 'Football icon.', 'country': 'United Kingdom'},
    {'name': 'The Avengers', 'follower_count': 9000000, 'description': 'Blockbuster superhero film.', 'country': 'United States'},
    {'name': 'The Office', 'follower_count': 7000000, 'description': 'Popular TV sitcom.', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 20000000, 'description': 'Actor and former wrestler.', 'country': 'United States'},
    {'name': 'Shakira', 'follower_count': 16000000, 'description': 'International pop star.', 'country': 'Colombia'},
    {'name': 'Woodrow Wilson', 'follower_count': 1800000, 'description': '28th President of the United States.', 'country': 'United States'},
    {'name': 'Intel', 'follower_count': 8000000, 'description': 'Leading semiconductor company.', 'country': 'United States'},
    {'name': 'OnePlus', 'follower_count': 4000000, 'description': 'Popular smartphone brand.', 'country': 'China'},
    {'name': 'Assassin’s Creed', 'follower_count': 9000000, 'description': 'Popular video game series.', 'country': 'Canada'},
    {'name': 'Evander Holyfield', 'follower_count': 1400000, 'description': 'Former heavyweight boxing champion.', 'country': 'United States'}
]
